# Generated by Django 4.0.5 on 2022-06-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('oid', models.UUIDField(db_index=True, editable=False, help_text='Object ID of the rule. Stable with different updates of the rule.')),
                ('vid', models.UUIDField(editable=False, help_text='Unique ID of the version of the rule. Changes with each update.', primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(auto_now=True, db_index=True, help_text='The moment this version was created')),
                ('ts_end', models.DateTimeField(blank=True, editable=False, help_text='The moment the rule is no longer is valid', null=True)),
                ('op', models.CharField(choices=[('C', 'Create'), ('U', 'Update'), ('D', 'Delete')], default='A', editable=False, help_text='Operation of this version', max_length=1)),
                ('name', models.TextField(help_text='Nombre de la persona que hizo el compromiso')),
                ('amount', models.DecimalField(decimal_places=3, help_text='Cuanto va a pagar', max_digits=14)),
                ('payday', models.TextField(help_text='Cuando va a pagar')),
                ('autor', models.TextField(help_text='Ejecutivo que registro el compromiso')),
            ],
            options={
                'get_latest_by': 'ts',
                'abstract': False,
                'unique_together': {('ts_end', 'oid')},
            },
        ),
    ]
